// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'banner': string;
  'body': string;
  'icon': string;
  'spin': string;
  'spinner': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
