// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'caption': string;
  'empty': string;
  'grid': string;
  'image': string;
  'selected': string;
  'sourceEdition': string;
  'sourceLabel': string;
  'sourceWork': string;
  'tile': string;
}
export const cssExports: CssExports;
export default cssExports;
