; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define AppName "Librarr"
#define AppPublisher "Librarr Project"
#define AppURL "https://github.com/Rorqualx/Librarr"
#define ForumsURL "https://github.com/Rorqualx/Librarr/discussions"
#define AppExeName "Readarr.exe"

; Version handling, reworked for the GitHub Actions release pipeline.
;
; The old script read MAJORVERSION and MINORVERSION, which only ever
; existed because Azure Pipelines exported its `majorVersion` /
; `minorVersion` variables into the environment. Nothing in GitHub Actions
; sets them, so both resolved to empty and `AppVersion=` alone is enough to
; make ISCC bail out.
;
; The deeper problem is VersionInfoVersion: it has to be a numeric dotted
; version, and the old script fed it `{BaseVersion}.{BuildNumber}`. Under
; the Librarr 1.x line that is "1.1.0-beta.3", which ISCC rejects outright
; ("Value of [Setup] section directive VersionInfoVersion is invalid").
; So derive everything from the single READARRVERSION the rest of the build
; already uses, and strip any prerelease suffix for the numeric field only.
#define BuildVersion GetEnv('READARRVERSION')
#if BuildVersion == ""
  ; Matches the Directory.Build.props placeholder a plain local build gets.
  #define BuildVersion "10.0.0.0"
#endif
#define NumericVersion BuildVersion
#if Pos("-", NumericVersion) > 0
  #define NumericVersion Copy(NumericVersion, 1, Pos("-", NumericVersion) - 1)
#endif

[Setup]
; NOTE: The value of AppId uniquely identifies this application.
; Do not use the same AppId value in installers for other applications.
; Fresh GUID so Windows tracks a Librarr install separately from a stock
; Readarr one. Note that this does NOT make the two co-installable: both
; register the same Windows service name (ServiceProvider.SERVICE_NAME is
; still "Readarr"), and PrepareToInstall below stops and deletes it. The
; supported path is migration, not coexistence.
AppId={{FA3F8C19-9179-4676-B7A9-B8F9B411711A}
AppName={#AppName}
AppVersion={#BuildVersion}
AppPublisher={#AppPublisher}
AppPublisherURL={#AppURL}
AppSupportURL={#ForumsURL}
AppUpdatesURL={#AppURL}
; \Librarr, not the inherited \Readarr. Two reasons, both concrete:
; AppFolderInfo.cs:36 already resolves AppDataFolder to
; %ProgramData%\Librarr, so installing into \Readarr scattered the
; binaries away from the data the app actually uses; and [InstallDelete]
; below wipes {app}\bin, which under the old path would have deleted a
; stock Readarr installation's binaries out from under it.
DefaultDirName={commonappdata}\Librarr
DisableDirPage=yes
DefaultGroupName={#AppName}
DisableProgramGroupPage=yes
; Matches the naming of every other release asset, with "-installer" to
; separate it from the portable Librarr.<version>.win-x64.zip that ships
; alongside it -- both land in the same release and .exe vs .zip alone is
; not an obvious enough distinction.
OutputBaseFilename=Librarr.{#BuildVersion}.{#Runtime}-installer
SolidCompression=yes
AppCopyright=GNU General Public License v3
AllowUNCPath=False
UninstallDisplayIcon={app}\bin\Readarr.exe
DisableReadyPage=True
CompressionThreads=2
Compression=lzma2/normal
AppContact={#ForumsURL}
VersionInfoVersion={#NumericVersion}
SetupLogging=yes
OutputDir=output
WizardStyle=modern

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopIcon"; Description: "{cm:CreateDesktopIcon}"
Name: "windowsService"; Description: "Install Windows Service (Starts when the computer starts as the LocalService user, you will need to change the user to access network shares)"; GroupDescription: "Start automatically"; Flags: exclusive
Name: "startupShortcut"; Description: "Create shortcut in Startup folder (Starts when you log into Windows)"; GroupDescription: "Start automatically"; Flags: exclusive unchecked
Name: "none"; Description: "Do not start automatically"; GroupDescription: "Start automatically"; Flags: exclusive unchecked

[Dirs]
Name: "{app}"; Permissions: users-modify

[Files]
Source: "..\..\..\_artifacts\{#Runtime}\{#Framework}\Readarr\Readarr.exe"; DestDir: "{app}\bin"; Flags: ignoreversion
Source: "..\..\..\_artifacts\{#Runtime}\{#Framework}\Readarr\*"; Excludes: "Readarr.Update"; DestDir: "{app}\bin"; Flags: ignoreversion recursesubdirs createallsubdirs
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{group}\{#AppName}"; Filename: "{app}\bin\{#AppExeName}"; Parameters: "/icon"
Name: "{commondesktop}\{#AppName}"; Filename: "{app}\bin\{#AppExeName}"; Parameters: "/icon"; Tasks: desktopIcon
Name: "{userstartup}\{#AppName}"; Filename: "{app}\bin\Readarr.exe"; WorkingDir: "{app}\bin"; Tasks: startupShortcut

[InstallDelete]
Name: "{app}\bin"; Type: filesandordirs

[Run]
Filename: "{app}\bin\Readarr.Console.exe"; StatusMsg: "Removing previous Windows Service"; Parameters: "/u /exitimmediately"; Flags: runhidden waituntilterminated;
Filename: "{app}\bin\Readarr.Console.exe"; Description: "Enable Access from Other Devices"; StatusMsg: "Enabling Remote access"; Parameters: "/registerurl /exitimmediately"; Flags: postinstall runascurrentuser runhidden waituntilterminated; Tasks: startupShortcut none;
Filename: "{app}\bin\Readarr.Console.exe"; StatusMsg: "Installing Windows Service"; Parameters: "/i /exitimmediately"; Flags: runhidden waituntilterminated; Tasks: windowsService
Filename: "{app}\bin\Readarr.exe"; Description: "Open Librarr Web UI"; Flags: postinstall skipifsilent nowait; Tasks: windowsService;
Filename: "{app}\bin\Readarr.exe"; Description: "Start Librarr"; Flags: postinstall skipifsilent nowait; Tasks: startupShortcut none;

[UninstallRun]
Filename: "{app}\bin\readarr.console.exe"; Parameters: "/u"; Flags: waituntilterminated skipifdoesntexist

[Code]
function PrepareToInstall(var NeedsRestart: Boolean): String;
var
  ResultCode: Integer;
begin
  Exec('net', 'stop readarr', '', 0, ewWaitUntilTerminated, ResultCode)
  Exec('sc', 'delete readarr', '', 0, ewWaitUntilTerminated, ResultCode)
end;
