// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'actionCell': string;
  'body': string;
  'confidenceLow': string;
  'confidenceMid': string;
  'empty': string;
  'olInput': string;
  'table': string;
}
export const cssExports: CssExports;
export default cssExports;
