// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'enabled': string;
  'name': string;
  'nameRow': string;
  'rescan': string;
  'rootFolder': string;
}
export const cssExports: CssExports;
export default cssExports;
