// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'author': string;
  'folder': string;
  'noMatches': string;
  'searchButton': string;
  'term': string;
}
export const cssExports: CssExports;
export default cssExports;
