// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'addRootFolder': string;
  'description': string;
  'path': string;
  'rootFolder': string;
  'rootFolders': string;
  'unmappedCount': string;
}
export const cssExports: CssExports;
export default cssExports;
