// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'importButton': string;
  'importContainer': string;
  'inputContainer': string;
  'label': string;
  'labelIcon': string;
}
export const cssExports: CssExports;
export default cssExports;
