// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'authorRow': string;
  'bookLink': string;
  'count': string;
  'empty': string;
  'error': string;
  'header': string;
  'list': string;
  'name': string;
  'row': string;
}
export const cssExports: CssExports;
export default cssExports;
